---
title: A03
author: R package build
date: '2022-03-28'
slug: a03
categories: []
tags: []
---

## Load Packages 
```{r}
library(openintro)
library(dplyr)
library(ggplot2)
library(gapminder)
library(tidyr)
library(ggridges)
library(patchwork)
library(rmarkdown)
glimpse(email)
```

```{r}
email %>%
  ggplot(aes(x = num_char, y = spam, fill = spam, color = spam)) +
geom_density_ridges2(alpha = 0.5) + 
  labs(
  x = "Number of characters (in thousands)", 
  y = "Spam", 
  title = "Spam vs. number of characters"
  ) +
  guides(color = FALSE, fill = FALSE) +
  scale_fill_manual(values = c("#E48957", "#CA235F")) +
  scale_color_manual(values = c("#DEB4A0", "#CA235F"))
```

```{r}
email %>%
  group_by(spam) %>%
  summarise(mean_num_char = mean(num_char))
```

# Would you expect emails that have subjects starting with "Re:", "RE:", "re:', or "rE:' to be spam or not?
```{r}
email %>%
  ggplot(aes(x = re_subj, fill = spam)) +
  geom_bar(position = "fill") +
  labs(
    x = 'Whether "re:", "RE:", etc. was in the email subject.',
    fill = "Spam",
    y = NULL,
    title = 'Spam vs. "re:" in subject'
  ) +
  scale_fill_manual(values = c("#DEB4A0", "#CA235F"))
```



