---
title: A02 REDO
author: R package build
date: '2022-04-02'
slug: a02-redo
categories: []
tags: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>
<script src="{{< blogdown/postref >}}index_files/kePrint/kePrint.js"></script>
<link href="{{< blogdown/postref >}}index_files/lightable/lightable.css" rel="stylesheet" />


<div id="summary" class="section level2">
<h2>Summary</h2>
<div id="a-professor-of-machine-learning-is-planning-to-get-married-to-his-long-time-girlfriend.-he-has-never-shopped-for-diamonds-before.-in-the-mall-he-was-confronted-with-a-dizzying-array-of-diamond-characteristics-configurations-and-pricing.-his-quick-search-revealed-that-diamonds-are-primarily-characterized-by-4c-viz.-color-cut-carat-weight-and-clarity-besides-polish-symmetry-and-certification.-he-scrapped-the-web-to-collect-information-from-three-different-wholesaler-websites-to-build-his-pricing-model-to-ensure-he-does-not-get-cheated-while-purchasing-the-diamond-ring.-build-a-linear-regression-model-to-predict-the-price-of-the-diamond-ring-of-his-interest." class="section level5">
<h5>A professor of machine learning is planning to get married to his long-time girlfriend. He has never shopped for diamonds before. In the mall, he was confronted with a dizzying array of diamond characteristics, configurations, and pricing. His quick search revealed that diamonds are primarily characterized by 4C viz. Color, Cut, Carat Weight and Clarity besides Polish, Symmetry, and certification. He scrapped the web to collect information from three different wholesaler websites to build his pricing model to ensure he does not get cheated while purchasing the diamond ring. Build a Linear Regression Model to predict the price of the diamond ring of his interest.</h5>
</div>
</div>
<div id="load-library" class="section level2">
<h2>Load Library</h2>
<pre class="r"><code>suppressPackageStartupMessages(library(&quot;ggplot2&quot;))
suppressPackageStartupMessages(library(&quot;dplyr&quot;))
suppressPackageStartupMessages(library(&quot;finalfit&quot;))
suppressPackageStartupMessages(library(&quot;memisc&quot;))
suppressPackageStartupMessages(library(&quot;summarytools&quot;))
suppressPackageStartupMessages(library(&quot;janitor&quot;))
suppressPackageStartupMessages(library(&quot;epiDisplay&quot;))
suppressPackageStartupMessages(library(&quot;sjPlot&quot;))
suppressPackageStartupMessages(library(&quot;sjmisc&quot;))
suppressPackageStartupMessages(library(&quot;sjlabelled&quot;))</code></pre>
</div>
<div id="import-data" class="section level2">
<h2>Import Data</h2>
<pre class="r"><code>professor.proposes.data &lt;- read.csv(&quot;https://raw.githubusercontent.com/JennaLeali/JennaLealisWebsite/main/Professor_Proposes_Data-3.csv&quot;)
head(professor.proposes.data)</code></pre>
<pre><code>##   Carat Colour Clarity Cut Certification Polish Symmetry Price Wholesaler
## 1  0.92      I     SI2   G           AGS      V        V  3000          1
## 2  0.92      I     SI2   V           AGS      G        G  3000          1
## 3  0.82      F     SI2   I           GIA      X        X  3004          1
## 4  0.81      G     SI1   I           GIA      X        V  3004          1
## 5  0.90      J     VS2   V           GIA      V        V  3006          1
## 6  0.87      F     SI2   I           AGS      G        V  3007          1</code></pre>
</div>
<div id="summary-of-data" class="section level2">
<h2>Summary of Data</h2>
<pre class="r"><code>summary(professor.proposes.data)</code></pre>
<pre><code>##      Carat           Colour            Clarity              Cut           
##  Min.   :0.0900   Length:440         Length:440         Length:440        
##  1st Qu.:0.3000   Class :character   Class :character   Class :character  
##  Median :0.8100   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :0.6693                                                           
##  3rd Qu.:1.0100                                                           
##  Max.   :1.5800                                                           
##  Certification         Polish            Symmetry             Price     
##  Length:440         Length:440         Length:440         Min.   : 160  
##  Class :character   Class :character   Class :character   1st Qu.: 520  
##  Mode  :character   Mode  :character   Mode  :character   Median :2169  
##                                                           Mean   :1717  
##                                                           3rd Qu.:3012  
##                                                           Max.   :3145  
##    Wholesaler   
##  Min.   :1.000  
##  1st Qu.:2.000  
##  Median :2.000  
##  Mean   :2.318  
##  3rd Qu.:3.000  
##  Max.   :3.000</code></pre>
<pre class="r"><code>str(professor.proposes.data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    440 obs. of  9 variables:
##  $ Carat        : num  0.92 0.92 0.82 0.81 0.9 0.87 0.8 0.84 0.8 0.8 ...
##  $ Colour       : chr  &quot;I&quot; &quot;I&quot; &quot;F&quot; &quot;G&quot; ...
##  $ Clarity      : chr  &quot;SI2&quot; &quot;SI2&quot; &quot;SI2&quot; &quot;SI1&quot; ...
##  $ Cut          : chr  &quot;G&quot; &quot;V&quot; &quot;I&quot; &quot;I&quot; ...
##  $ Certification: chr  &quot;AGS&quot; &quot;AGS&quot; &quot;GIA&quot; &quot;GIA&quot; ...
##  $ Polish       : chr  &quot;V&quot; &quot;G&quot; &quot;X&quot; &quot;X&quot; ...
##  $ Symmetry     : chr  &quot;V&quot; &quot;G&quot; &quot;X&quot; &quot;V&quot; ...
##  $ Price        : int  3000 3000 3004 3004 3006 3007 3008 3010 3012 3012 ...
##  $ Wholesaler   : int  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<div id="dealing-with-duplicates" class="section level3">
<h3>Dealing with duplicates</h3>
<pre class="r"><code>duplicated_rows &lt;- professor.proposes.data[duplicated(professor.proposes.data),]
duplicated_rows</code></pre>
<pre><code>##     Carat Colour Clarity Cut Certification Polish Symmetry Price Wholesaler
## 23   0.80      I     VS1   I           AGS      I        I  3031          1
## 172  1.01      J     SI2   X           EGL      V        V  3139          2
## 173  1.01      J     SI2   X           EGL      V        V  3139          2
## 174  1.01      J     SI2   I           EGL      V        X  3139          2
## 275  0.22      F     SI1   V           IGI      G        G   330          3
## 283  0.23      F     SI1   X           IGI      G        G   360          3
## 286  0.28      E    VVS2   X           GIA      V        X   658          3
## 307  0.30      H     SI2   X           GIA      V        V   493          3
## 309  0.30      H     SI2   X           GIA      V        V   493          3
## 310  0.30      H     SI2   X           GIA      V        V   493          3
## 317  0.30      J     VS2   V           GIA      V        V   493          3
## 318  0.30      J     VS2   X           GIA      V        V   493          3
## 326  0.30      F     SI2   V           GIA      V        V   520          3
## 330  0.30      F     SI2   I           GIA      V        V   520          3
## 332  0.30      F     SI2   I           GIA      V        V   520          3
## 333  0.30      F     SI2   V           GIA      V        V   520          3
## 334  0.30      F     SI2   V           GIA      V        V   520          3
## 337  0.30      G     SI2   I           GIA      V        V   520          3
## 347  0.30      G     SI2   X           GIA      V        V   520          3
## 350  0.30      I     SI1   V           GIA      V        V   520          3
## 352  0.30      I     SI1   V           GIA      V        V   520          3
## 353  0.30      I     SI1   V           GIA      V        V   520          3
## 358  0.30      I     SI1   I           GIA      V        V   520          3
## 359  0.30      I     SI1   I           GIA      V        V   520          3
## 360  0.30      I     SI1   V           GIA      V        V   520          3
## 367  0.30      J     VS1   V           GIA      V        V   520          3
## 368  0.30      J     VS1   X           GIA      V        V   520          3
## 369  0.30      J     VS1   V           GIA      V        V   520          3
## 371  0.30      J     VS1   X           GIA      V        V   520          3
## 373  0.30      J     VS1   X           GIA      V        V   520          3
## 376  0.30      J     VS1   V           GIA      V        V   520          3
## 393  0.30      H     SI1   V           GIA      V        G   547          3
## 401  0.30      H     SI1   X           GIA      V        V   547          3
## 403  0.30      H     SI1   X           GIA      G        G   547          3
## 406  0.30      H     SI1   V           GIA      X        V   547          3
## 408  0.30      H     SI1   V           GIA      V        V   547          3
## 409  0.30      H     SI1   X           GIA      V        V   547          3
## 410  0.30      H     SI1   V           GIA      X        V   547          3
## 412  0.30      H     SI1   V           GIA      V        V   547          3
## 413  0.30      H     SI1   V           GIA      X        V   547          3
## 414  0.30      H     SI1   X           GIA      V        V   547          3
## 415  0.30      H     SI1   X           GIA      V        V   547          3
## 416  0.30      H     SI1   X           GIA      V        V   547          3
## 418  0.30      H     SI1   V           GIA      X        V   547          3
## 419  0.30      H     SI1   X           GIA      V        V   547          3
## 426  0.30      I     VS2   I           GIA      V        V   547          3
## 427  0.30      I     VS2   X           GIA      V        V   547          3
## 430  0.30      I     VS2   X           GIA      X        V   547          3
## 432  0.30      I     VS2   I           GIA      G        V   547          3
## 433  0.30      I     VS2   I           GIA      X        V   547          3
## 434  0.30      I     VS2   I           GIA      X        V   547          3</code></pre>
</div>
<div id="dealing-with-missing-data" class="section level3">
<h3>Dealing with missing data</h3>
<pre class="r"><code>sum(is.na(professor.proposes.data))</code></pre>
<pre><code>## [1] 0</code></pre>
</div>
</div>
<div id="univariate-analysis-metric-data" class="section level2">
<h2>Univariate Analysis Metric Data</h2>
<div id="numerical-varaibles" class="section level4">
<h4>Numerical Varaibles</h4>
<pre class="r"><code>library(psych)</code></pre>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:epiDisplay&#39;:
## 
##     alpha, cs, lookup</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<pre class="r"><code>describe(professor.proposes.data)</code></pre>
<pre><code>##                vars   n    mean      sd  median trimmed     mad    min     max
## Carat             1 440    0.67    0.38    0.81    0.67    0.53   0.09    1.58
## Colour*           2 440    4.92    2.09    5.00    4.92    2.97   1.00    9.00
## Clarity*          3 440    3.60    1.89    3.00    3.47    1.48   1.00    9.00
## Cut*              4 440    3.52    1.40    4.00    3.65    1.48   1.00    5.00
## Certification*    5 440    3.74    0.75    4.00    3.75    0.00   1.00    5.00
## Polish*           6 440    3.94    1.62    5.00    3.94    1.48   1.00    6.00
## Symmetry*         7 440    3.25    1.19    4.00    3.24    1.48   1.00    5.00
## Price             8 440 1716.74 1175.69 2169.00 1722.32 1422.55 160.00 3145.00
## Wholesaler        9 440    2.32    0.70    2.00    2.40    1.48   1.00    3.00
##                  range  skew kurtosis    se
## Carat             1.49 -0.05    -1.67  0.02
## Colour*           8.00 -0.12    -0.97  0.10
## Clarity*          8.00  0.50    -0.23  0.09
## Cut*              4.00 -0.52    -1.01  0.07
## Certification*    4.00 -1.15     3.09  0.04
## Polish*           5.00 -0.30    -1.66  0.08
## Symmetry*         4.00 -0.24    -1.35  0.06
## Price          2985.00 -0.05    -1.83 56.05
## Wholesaler        2.00 -0.53    -0.87  0.03</code></pre>
</div>
<div id="categorical-variables" class="section level4">
<h4>Categorical variables</h4>
<pre class="r"><code>getmode &lt;- function(v) {
   uniqv &lt;- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
mode &lt;- getmode(professor.proposes.data$Clarity)
mode</code></pre>
<pre><code>## [1] &quot;SI1&quot;</code></pre>
<pre class="r"><code>dfSummary(professor.proposes.data)</code></pre>
<pre><code>## Data Frame Summary  
## professor.proposes.data  
## Dimensions: 440 x 9  
## Duplicates: 51  
## 
## --------------------------------------------------------------------------------------------------------------
## No   Variable        Stats / Values                Freqs (% of Valid)    Graph            Valid      Missing  
## ---- --------------- ----------------------------- --------------------- ---------------- ---------- ---------
## 1    Carat           Mean (sd) : 0.7 (0.4)         50 distinct values      :              440        0        
##      [numeric]       min &lt; med &lt; max:                                      :       .      (100.0%)   (0.0%)   
##                      0.1 &lt; 0.8 &lt; 1.6                                       :     . :                          
##                      IQR (CV) : 0.7 (0.6)                                  :     : :                          
##                                                                          . :   . : : .                        
## 
## 2    Colour          1. D                          20 ( 4.5%)                             440        0        
##      [character]     2. E                          54 (12.3%)            II               (100.0%)   (0.0%)   
##                      3. F                          58 (13.2%)            II                                   
##                      4. G                          43 ( 9.8%)            I                                    
##                      5. H                          71 (16.1%)            III                                  
##                      6. I                          79 (18.0%)            III                                  
##                      7. J                          72 (16.4%)            III                                  
##                      8. K                          31 ( 7.0%)            I                                    
##                      9. L                          12 ( 2.7%)                                                 
## 
## 3    Clarity         1. I1                          82 (18.6%)           III              440        0        
##      [character]     2. I2                          28 ( 6.4%)           I                (100.0%)   (0.0%)   
##                      3. SI1                        116 (26.4%)           IIIII                                
##                      4. SI2                        110 (25.0%)           IIIII                                
##                      5. SI3                         26 ( 5.9%)           I                                    
##                      6. VS1                         30 ( 6.8%)           I                                    
##                      7. VS2                         41 ( 9.3%)           I                                    
##                      8. VVS1                         2 ( 0.5%)                                                
##                      9. VVS2                         5 ( 1.1%)                                                
## 
## 4    Cut             1. F                           59 (13.4%)           II               440        0        
##      [character]     2. G                           49 (11.1%)           II               (100.0%)   (0.0%)   
##                      3. I                           86 (19.5%)           III                                  
##                      4. V                           97 (22.0%)           IIII                                 
##                      5. X                          149 (33.9%)           IIIIII                               
## 
## 5    Certification   1. AGS                         12 ( 2.7%)                            440        0        
##      [character]     2. DOW                          1 ( 0.2%)                            (100.0%)   (0.0%)   
##                      3. EGL                        119 (27.0%)           IIIII                                
##                      4. GIA                        265 (60.2%)           IIIIIIIIIIII                         
##                      5. IGI                         43 ( 9.8%)           I                                    
## 
## 6    Polish          1. F                            5 ( 1.1%)                            440        0        
##      [character]     2. G                          165 (37.5%)           IIIIIII          (100.0%)   (0.0%)   
##                      3. I                            5 ( 1.1%)                                                
##                      4. v                            1 ( 0.2%)                                                
##                      5. V                          203 (46.1%)           IIIIIIIII                            
##                      6. X                           61 (13.9%)           II                                   
## 
## 7    Symmetry        1. F                           21 ( 4.8%)                            440        0        
##      [character]     2. G                          157 (35.7%)           IIIIIII          (100.0%)   (0.0%)   
##                      3. I                            5 ( 1.1%)                                                
##                      4. V                          206 (46.8%)           IIIIIIIII                            
##                      5. X                           51 (11.6%)           II                                   
## 
## 8    Price           Mean (sd) : 1716.7 (1175.7)   197 distinct values     :         .    440        0        
##      [integer]       min &lt; med &lt; max:                                      :         :    (100.0%)   (0.0%)   
##                      160 &lt; 2169 &lt; 3145                                   : :     .   :                        
##                      IQR (CV) : 2492.5 (0.7)                             : :     : : :                        
##                                                                          : :   . : : :                        
## 
## 9    Wholesaler      Mean (sd) : 2.3 (0.7)         1 :  60 (13.6%)       II               440        0        
##      [integer]       min &lt; med &lt; max:              2 : 180 (40.9%)       IIIIIIII         (100.0%)   (0.0%)   
##                      1 &lt; 2 &lt; 3                     3 : 200 (45.5%)       IIIIIIIII                            
##                      IQR (CV) : 1 (0.3)                                                                       
## --------------------------------------------------------------------------------------------------------------</code></pre>
<pre class="r"><code>library(vtable)</code></pre>
<pre><code>## Loading required package: kableExtra</code></pre>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
<pre class="r"><code>st(professor.proposes.data)</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-10">Table 1: </span>Summary Statistics
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
N
</th>
<th style="text-align:left;">
Mean
</th>
<th style="text-align:left;">
Std. Dev.
</th>
<th style="text-align:left;">
Min
</th>
<th style="text-align:left;">
Pctl. 25
</th>
<th style="text-align:left;">
Pctl. 75
</th>
<th style="text-align:left;">
Max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Carat
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
0.669
</td>
<td style="text-align:left;">
0.38
</td>
<td style="text-align:left;">
0.09
</td>
<td style="text-align:left;">
0.3
</td>
<td style="text-align:left;">
1.01
</td>
<td style="text-align:left;">
1.58
</td>
</tr>
<tr>
<td style="text-align:left;">
Cut
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… F
</td>
<td style="text-align:left;">
59
</td>
<td style="text-align:left;">
13.4%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… G
</td>
<td style="text-align:left;">
49
</td>
<td style="text-align:left;">
11.1%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… I
</td>
<td style="text-align:left;">
86
</td>
<td style="text-align:left;">
19.5%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… V
</td>
<td style="text-align:left;">
97
</td>
<td style="text-align:left;">
22%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… X
</td>
<td style="text-align:left;">
149
</td>
<td style="text-align:left;">
33.9%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Certification
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… AGS
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
2.7%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… DOW
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.2%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… EGL
</td>
<td style="text-align:left;">
119
</td>
<td style="text-align:left;">
27%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… GIA
</td>
<td style="text-align:left;">
265
</td>
<td style="text-align:left;">
60.2%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… IGI
</td>
<td style="text-align:left;">
43
</td>
<td style="text-align:left;">
9.8%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Polish
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… F
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
1.1%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… G
</td>
<td style="text-align:left;">
165
</td>
<td style="text-align:left;">
37.5%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… I
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
1.1%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… v
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.2%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… V
</td>
<td style="text-align:left;">
203
</td>
<td style="text-align:left;">
46.1%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… X
</td>
<td style="text-align:left;">
61
</td>
<td style="text-align:left;">
13.9%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Symmetry
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… F
</td>
<td style="text-align:left;">
21
</td>
<td style="text-align:left;">
4.8%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… G
</td>
<td style="text-align:left;">
157
</td>
<td style="text-align:left;">
35.7%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… I
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
1.1%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… V
</td>
<td style="text-align:left;">
206
</td>
<td style="text-align:left;">
46.8%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… X
</td>
<td style="text-align:left;">
51
</td>
<td style="text-align:left;">
11.6%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Price
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
1716.739
</td>
<td style="text-align:left;">
1175.689
</td>
<td style="text-align:left;">
160
</td>
<td style="text-align:left;">
520
</td>
<td style="text-align:left;">
3012.5
</td>
<td style="text-align:left;">
3145
</td>
</tr>
<tr>
<td style="text-align:left;">
Wholesaler
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
2.318
</td>
<td style="text-align:left;">
0.701
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>st(professor.proposes.data, col.breaks = 4,
   summ = list(
     c(&#39;notNA(x)&#39;,&#39;mean(x)&#39;,&#39;sd(x^2)&#39;,&#39;min(x)&#39;,&#39;max(x)&#39;),
     c(&#39;notNA(x)&#39;,&#39;mean(x)&#39;)
   ),
   summ.names = list(
     c(&#39;N&#39;,&#39;Mean&#39;,&#39;SD of X^2&#39;,&#39;Min&#39;,&#39;Max&#39;),
     c(&#39;Count&#39;,&#39;Percent&#39;)
   ))</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-11">Table 2: </span>Summary Statistics
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
N
</th>
<th style="text-align:left;">
Mean
</th>
<th style="text-align:left;">
SD of X^2
</th>
<th style="text-align:left;">
Min
</th>
<th style="text-align:left;">
Max
</th>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
Count
</th>
<th style="text-align:left;">
Percent
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Carat
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
0.669
</td>
<td style="text-align:left;">
0.508
</td>
<td style="text-align:left;">
0.09
</td>
<td style="text-align:left;">
1.58
</td>
<td style="text-align:left;">
Symmetry
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Cut
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
… F
</td>
<td style="text-align:left;">
21
</td>
<td style="text-align:left;">
4.8%
</td>
</tr>
<tr>
<td style="text-align:left;">
… F
</td>
<td style="text-align:left;">
59
</td>
<td style="text-align:left;">
13.4%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
… G
</td>
<td style="text-align:left;">
157
</td>
<td style="text-align:left;">
35.7%
</td>
</tr>
<tr>
<td style="text-align:left;">
… G
</td>
<td style="text-align:left;">
49
</td>
<td style="text-align:left;">
11.1%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
… I
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
1.1%
</td>
</tr>
<tr>
<td style="text-align:left;">
… I
</td>
<td style="text-align:left;">
86
</td>
<td style="text-align:left;">
19.5%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
… V
</td>
<td style="text-align:left;">
206
</td>
<td style="text-align:left;">
46.8%
</td>
</tr>
<tr>
<td style="text-align:left;">
… V
</td>
<td style="text-align:left;">
97
</td>
<td style="text-align:left;">
22%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
… X
</td>
<td style="text-align:left;">
51
</td>
<td style="text-align:left;">
11.6%
</td>
</tr>
<tr>
<td style="text-align:left;">
… X
</td>
<td style="text-align:left;">
149
</td>
<td style="text-align:left;">
33.9%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Price
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
1716.739
</td>
</tr>
<tr>
<td style="text-align:left;">
Certification
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Wholesaler
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
2.318
</td>
</tr>
<tr>
<td style="text-align:left;">
… AGS
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
2.7%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… DOW
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.2%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… EGL
</td>
<td style="text-align:left;">
119
</td>
<td style="text-align:left;">
27%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… GIA
</td>
<td style="text-align:left;">
265
</td>
<td style="text-align:left;">
60.2%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… IGI
</td>
<td style="text-align:left;">
43
</td>
<td style="text-align:left;">
9.8%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Polish
</td>
<td style="text-align:left;">
440
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… F
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
1.1%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… G
</td>
<td style="text-align:left;">
165
</td>
<td style="text-align:left;">
37.5%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… I
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
1.1%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… v
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0.2%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… V
</td>
<td style="text-align:left;">
203
</td>
<td style="text-align:left;">
46.1%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
… X
</td>
<td style="text-align:left;">
61
</td>
<td style="text-align:left;">
13.9%
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table>
</div>
<div id="the-price-ranged-from-160-to-3145-and-had-bimodal-distribution.-the-diamonds-appear-to-be-in-two-clusters-less-than-1000-and-higher-than-1000" class="section level4">
<h4>The Price ranged from 160 to 3145 and had bimodal distribution. The diamonds appear to be in two clusters less than 1000 and higher than 1000</h4>
</div>
<div id="the-carat-ranged-from-0.09-to-1.58-and-had-bimodal-distribution.-the-diamonds-appear-to-be-in-two-clusters-0.09-to-0.30-and-0.81-to-1.58-carats." class="section level4">
<h4>The Carat ranged from 0.09 to 1.58 and had bimodal distribution. The diamonds appear to be in two clusters 0.09 to 0.30 and 0.81 to 1.58 carats.</h4>
</div>
</div>
<div id="explority-data-analysis" class="section level2">
<h2>Explority Data Analysis</h2>
<pre class="r"><code>summarytools::freq(professor.proposes.data$Carat, order = &quot;freq&quot;)</code></pre>
<pre><code>## Frequencies  
## professor.proposes.data$Carat  
## Type: Numeric  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##         0.3    154     35.00          35.00     35.00          35.00
##           1     51     11.59          46.59     11.59          46.59
##        1.01     42      9.55          56.14      9.55          56.14
##         0.8     15      3.41          59.55      3.41          59.55
##         0.1     13      2.95          62.50      2.95          62.50
##        0.81     13      2.95          65.45      2.95          65.45
##        1.02     13      2.95          68.41      2.95          68.41
##         0.9     11      2.50          70.91      2.50          70.91
##        1.04     10      2.27          73.18      2.27          73.18
##        1.03      8      1.82          75.00      1.82          75.00
##        0.21      7      1.59          76.59      1.59          76.59
##        0.23      7      1.59          78.18      1.59          78.18
##         1.1      6      1.36          79.55      1.36          79.55
##        0.09      5      1.14          80.68      1.14          80.68
##        0.11      5      1.14          81.82      1.14          81.82
##        0.22      5      1.14          82.95      1.14          82.95
##        0.82      5      1.14          84.09      1.14          84.09
##        1.05      5      1.14          85.23      1.14          85.23
##        0.91      4      0.91          86.14      0.91          86.14
##        1.16      4      0.91          87.05      0.91          87.05
##        0.83      3      0.68          87.73      0.68          87.73
##        0.85      3      0.68          88.41      0.68          88.41
##        0.92      3      0.68          89.09      0.68          89.09
##        1.06      3      0.68          89.77      0.68          89.77
##        1.07      3      0.68          90.45      0.68          90.45
##        1.11      3      0.68          91.14      0.68          91.14
##        1.12      3      0.68          91.82      0.68          91.82
##        1.14      3      0.68          92.50      0.68          92.50
##        1.15      3      0.68          93.18      0.68          93.18
##         1.2      3      0.68          93.86      0.68          93.86
##        1.21      3      0.68          94.55      0.68          94.55
##        1.23      3      0.68          95.23      0.68          95.23
##        0.28      2      0.45          95.68      0.45          95.68
##        1.09      2      0.45          96.14      0.45          96.14
##        1.19      2      0.45          96.59      0.45          96.59
##         0.2      1      0.23          96.82      0.23          96.82
##        0.27      1      0.23          97.05      0.23          97.05
##        0.84      1      0.23          97.27      0.23          97.27
##        0.87      1      0.23          97.50      0.23          97.50
##        0.88      1      0.23          97.73      0.23          97.73
##        1.13      1      0.23          97.95      0.23          97.95
##        1.17      1      0.23          98.18      0.23          98.18
##        1.18      1      0.23          98.41      0.23          98.41
##        1.22      1      0.23          98.64      0.23          98.64
##        1.25      1      0.23          98.86      0.23          98.86
##        1.26      1      0.23          99.09      0.23          99.09
##        1.33      1      0.23          99.32      0.23          99.32
##        1.41      1      0.23          99.55      0.23          99.55
##        1.43      1      0.23          99.77      0.23          99.77
##        1.58      1      0.23         100.00      0.23         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total    440    100.00         100.00    100.00         100.00</code></pre>
<pre class="r"><code>tabyl(professor.proposes.data$Carat, sort = TRUE)</code></pre>
<pre><code>##  professor.proposes.data$Carat   n     percent
##                           0.09   5 0.011363636
##                           0.10  13 0.029545455
##                           0.11   5 0.011363636
##                           0.20   1 0.002272727
##                           0.21   7 0.015909091
##                           0.22   5 0.011363636
##                           0.23   7 0.015909091
##                           0.27   1 0.002272727
##                           0.28   2 0.004545455
##                           0.30 154 0.350000000
##                           0.80  15 0.034090909
##                           0.81  13 0.029545455
##                           0.82   5 0.011363636
##                           0.83   3 0.006818182
##                           0.84   1 0.002272727
##                           0.85   3 0.006818182
##                           0.87   1 0.002272727
##                           0.88   1 0.002272727
##                           0.90  11 0.025000000
##                           0.91   4 0.009090909
##                           0.92   3 0.006818182
##                           1.00  51 0.115909091
##                           1.01  42 0.095454545
##                           1.02  13 0.029545455
##                           1.03   8 0.018181818
##                           1.04  10 0.022727273
##                           1.05   5 0.011363636
##                           1.06   3 0.006818182
##                           1.07   3 0.006818182
##                           1.09   2 0.004545455
##                           1.10   6 0.013636364
##                           1.11   3 0.006818182
##                           1.12   3 0.006818182
##                           1.13   1 0.002272727
##                           1.14   3 0.006818182
##                           1.15   3 0.006818182
##                           1.16   4 0.009090909
##                           1.17   1 0.002272727
##                           1.18   1 0.002272727
##                           1.19   2 0.004545455
##                           1.20   3 0.006818182
##                           1.21   3 0.006818182
##                           1.22   1 0.002272727
##                           1.23   3 0.006818182
##                           1.25   1 0.002272727
##                           1.26   1 0.002272727
##                           1.33   1 0.002272727
##                           1.41   1 0.002272727
##                           1.43   1 0.002272727
##                           1.58   1 0.002272727</code></pre>
<pre class="r"><code>tab1(professor.proposes.data$Carat, sort.group = &quot;decreasing&quot;, cum.percent = TRUE)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre><code>## professor.proposes.data$Carat : 
##         Frequency Percent Cum. percent
## 0.3           154    35.0         35.0
## 1              51    11.6         46.6
## 1.01           42     9.5         56.1
## 0.8            15     3.4         59.5
## 1.02           13     3.0         62.5
## 0.81           13     3.0         65.5
## 0.1            13     3.0         68.4
## 0.9            11     2.5         70.9
## 1.04           10     2.3         73.2
## 1.03            8     1.8         75.0
## 0.23            7     1.6         76.6
## 0.21            7     1.6         78.2
## 1.1             6     1.4         79.5
## 1.05            5     1.1         80.7
## 0.82            5     1.1         81.8
## 0.22            5     1.1         83.0
## 0.11            5     1.1         84.1
## 0.09            5     1.1         85.2
## 1.16            4     0.9         86.1
## 0.91            4     0.9         87.0
## 1.23            3     0.7         87.7
## 1.21            3     0.7         88.4
## 1.2             3     0.7         89.1
## 1.15            3     0.7         89.8
## 1.14            3     0.7         90.5
## 1.12            3     0.7         91.1
## 1.11            3     0.7         91.8
## 1.07            3     0.7         92.5
## 1.06            3     0.7         93.2
## 0.92            3     0.7         93.9
## 0.85            3     0.7         94.5
## 0.83            3     0.7         95.2
## 1.19            2     0.5         95.7
## 1.09            2     0.5         96.1
## 0.28            2     0.5         96.6
## 1.58            1     0.2         96.8
## 1.43            1     0.2         97.0
## 1.41            1     0.2         97.3
## 1.33            1     0.2         97.5
## 1.26            1     0.2         97.7
## 1.25            1     0.2         98.0
## 1.22            1     0.2         98.2
## 1.18            1     0.2         98.4
## 1.17            1     0.2         98.6
## 1.13            1     0.2         98.9
## 0.88            1     0.2         99.1
## 0.87            1     0.2         99.3
## 0.84            1     0.2         99.5
## 0.27            1     0.2         99.8
## 0.2             1     0.2        100.0
##   Total       440   100.0        100.0</code></pre>
<pre class="r"><code>summarytools::freq(professor.proposes.data$Clarity, order = &quot;freq&quot;)</code></pre>
<pre><code>## Frequencies  
## professor.proposes.data$Clarity  
## Type: Character  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##         SI1    116     26.36          26.36     26.36          26.36
##         SI2    110     25.00          51.36     25.00          51.36
##          I1     82     18.64          70.00     18.64          70.00
##         VS2     41      9.32          79.32      9.32          79.32
##         VS1     30      6.82          86.14      6.82          86.14
##          I2     28      6.36          92.50      6.36          92.50
##         SI3     26      5.91          98.41      5.91          98.41
##        VVS2      5      1.14          99.55      1.14          99.55
##        VVS1      2      0.45         100.00      0.45         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total    440    100.00         100.00    100.00         100.00</code></pre>
<pre class="r"><code>tabyl(professor.proposes.data$Clarity, sort = TRUE)</code></pre>
<pre><code>##  professor.proposes.data$Clarity   n     percent
##                               I1  82 0.186363636
##                               I2  28 0.063636364
##                              SI1 116 0.263636364
##                              SI2 110 0.250000000
##                              SI3  26 0.059090909
##                              VS1  30 0.068181818
##                              VS2  41 0.093181818
##                             VVS1   2 0.004545455
##                             VVS2   5 0.011363636</code></pre>
<pre class="r"><code>tab1(professor.proposes.data$Clarity, sort.group = &quot;decreasing&quot;, cum.percent = TRUE)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre><code>## professor.proposes.data$Clarity : 
##         Frequency Percent Cum. percent
## SI1           116    26.4         26.4
## SI2           110    25.0         51.4
## I1             82    18.6         70.0
## VS2            41     9.3         79.3
## VS1            30     6.8         86.1
## I2             28     6.4         92.5
## SI3            26     5.9         98.4
## VVS2            5     1.1         99.5
## VVS1            2     0.5        100.0
##   Total       440   100.0        100.0</code></pre>
<pre class="r"><code>summarytools::freq(professor.proposes.data$Colour, order = &quot;freq&quot;)</code></pre>
<pre><code>## Frequencies  
## professor.proposes.data$Colour  
## Type: Character  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##           I     79     17.95          17.95     17.95          17.95
##           J     72     16.36          34.32     16.36          34.32
##           H     71     16.14          50.45     16.14          50.45
##           F     58     13.18          63.64     13.18          63.64
##           E     54     12.27          75.91     12.27          75.91
##           G     43      9.77          85.68      9.77          85.68
##           K     31      7.05          92.73      7.05          92.73
##           D     20      4.55          97.27      4.55          97.27
##           L     12      2.73         100.00      2.73         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total    440    100.00         100.00    100.00         100.00</code></pre>
<pre class="r"><code>tabyl(professor.proposes.data$Colour, sort = TRUE)</code></pre>
<pre><code>##  professor.proposes.data$Colour  n    percent
##                               D 20 0.04545455
##                               E 54 0.12272727
##                               F 58 0.13181818
##                               G 43 0.09772727
##                               H 71 0.16136364
##                               I 79 0.17954545
##                               J 72 0.16363636
##                               K 31 0.07045455
##                               L 12 0.02727273</code></pre>
<pre class="r"><code>tab1(professor.proposes.data$Colour, sort.group = &quot;decreasing&quot;, cum.percent = TRUE)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre><code>## professor.proposes.data$Colour : 
##         Frequency Percent Cum. percent
## I              79    18.0         18.0
## J              72    16.4         34.3
## H              71    16.1         50.5
## F              58    13.2         63.6
## E              54    12.3         75.9
## G              43     9.8         85.7
## K              31     7.0         92.7
## D              20     4.5         97.3
## L              12     2.7        100.0
##   Total       440   100.0        100.0</code></pre>
<pre class="r"><code>summarytools::freq(professor.proposes.data$Cut, order = &quot;freq&quot;)</code></pre>
<pre><code>## Frequencies  
## professor.proposes.data$Cut  
## Type: Character  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##           X    149     33.86          33.86     33.86          33.86
##           V     97     22.05          55.91     22.05          55.91
##           I     86     19.55          75.45     19.55          75.45
##           F     59     13.41          88.86     13.41          88.86
##           G     49     11.14         100.00     11.14         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total    440    100.00         100.00    100.00         100.00</code></pre>
<pre class="r"><code>tabyl(professor.proposes.data$Cut, sort = TRUE)</code></pre>
<pre><code>##  professor.proposes.data$Cut   n   percent
##                            F  59 0.1340909
##                            G  49 0.1113636
##                            I  86 0.1954545
##                            V  97 0.2204545
##                            X 149 0.3386364</code></pre>
<pre class="r"><code>tab1(professor.proposes.data$Cut, sort.group = &quot;decreasing&quot;, cum.percent = TRUE)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre><code>## professor.proposes.data$Cut : 
##         Frequency Percent Cum. percent
## X             149    33.9         33.9
## V              97    22.0         55.9
## I              86    19.5         75.5
## F              59    13.4         88.9
## G              49    11.1        100.0
##   Total       440   100.0        100.0</code></pre>
<pre class="r"><code>summarytools::freq(professor.proposes.data$Certification, order = &quot;freq&quot;)</code></pre>
<pre><code>## Frequencies  
## professor.proposes.data$Certification  
## Type: Character  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##         GIA    265     60.23          60.23     60.23          60.23
##         EGL    119     27.05          87.27     27.05          87.27
##         IGI     43      9.77          97.05      9.77          97.05
##         AGS     12      2.73          99.77      2.73          99.77
##         DOW      1      0.23         100.00      0.23         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total    440    100.00         100.00    100.00         100.00</code></pre>
<pre class="r"><code>tabyl(professor.proposes.data$Certification, sort = TRUE)</code></pre>
<pre><code>##  professor.proposes.data$Certification   n     percent
##                                    AGS  12 0.027272727
##                                    DOW   1 0.002272727
##                                    EGL 119 0.270454545
##                                    GIA 265 0.602272727
##                                    IGI  43 0.097727273</code></pre>
<pre class="r"><code>tab1(professor.proposes.data$Certification, sort.group = &quot;decreasing&quot;, cum.percent = TRUE)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<pre><code>## professor.proposes.data$Certification : 
##         Frequency Percent Cum. percent
## GIA           265    60.2         60.2
## EGL           119    27.0         87.3
## IGI            43     9.8         97.0
## AGS            12     2.7         99.8
## DOW             1     0.2        100.0
##   Total       440   100.0        100.0</code></pre>
<pre class="r"><code>summarytools::freq(professor.proposes.data$Polish, order = &quot;freq&quot;)</code></pre>
<pre><code>## Frequencies  
## professor.proposes.data$Polish  
## Type: Character  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##           V    203     46.14          46.14     46.14          46.14
##           G    165     37.50          83.64     37.50          83.64
##           X     61     13.86          97.50     13.86          97.50
##           F      5      1.14          98.64      1.14          98.64
##           I      5      1.14          99.77      1.14          99.77
##           v      1      0.23         100.00      0.23         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total    440    100.00         100.00    100.00         100.00</code></pre>
<pre class="r"><code>tabyl(professor.proposes.data$Polish, sort = TRUE)</code></pre>
<pre><code>##  professor.proposes.data$Polish   n     percent
##                               F   5 0.011363636
##                               G 165 0.375000000
##                               I   5 0.011363636
##                               v   1 0.002272727
##                               V 203 0.461363636
##                               X  61 0.138636364</code></pre>
<pre class="r"><code>tab1(professor.proposes.data$Polish, sort.group = &quot;decreasing&quot;, cum.percent = TRUE)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<pre><code>## professor.proposes.data$Polish : 
##         Frequency Percent Cum. percent
## V             203    46.1         46.1
## G             165    37.5         83.6
## X              61    13.9         97.5
## I               5     1.1         98.6
## F               5     1.1         99.8
## v               1     0.2        100.0
##   Total       440   100.0        100.0</code></pre>
<pre class="r"><code>summarytools::freq(professor.proposes.data$Symmetry, order = &quot;freq&quot;)</code></pre>
<pre><code>## Frequencies  
## professor.proposes.data$Symmetry  
## Type: Character  
## 
##               Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
## ----------- ------ --------- -------------- --------- --------------
##           V    206     46.82          46.82     46.82          46.82
##           G    157     35.68          82.50     35.68          82.50
##           X     51     11.59          94.09     11.59          94.09
##           F     21      4.77          98.86      4.77          98.86
##           I      5      1.14         100.00      1.14         100.00
##        &lt;NA&gt;      0                               0.00         100.00
##       Total    440    100.00         100.00    100.00         100.00</code></pre>
<pre class="r"><code>tabyl(professor.proposes.data$Symmetry, sort = TRUE)</code></pre>
<pre><code>##  professor.proposes.data$Symmetry   n    percent
##                                 F  21 0.04772727
##                                 G 157 0.35681818
##                                 I   5 0.01136364
##                                 V 206 0.46818182
##                                 X  51 0.11590909</code></pre>
<pre class="r"><code>tab1(professor.proposes.data$Symmetry, sort.group = &quot;decreasing&quot;, cum.percent = TRUE)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<pre><code>## professor.proposes.data$Symmetry : 
##         Frequency Percent Cum. percent
## V             206    46.8         46.8
## G             157    35.7         82.5
## X              51    11.6         94.1
## F              21     4.8         98.9
## I               5     1.1        100.0
##   Total       440   100.0        100.0</code></pre>
<div id="range-and-interquartile-range-of-price" class="section level5">
<h5>Range and Interquartile Range of Price</h5>
<pre class="r"><code>professor.proposes.data %&gt;%
  summarize(max(Price) - min(Price), IQR(Price))</code></pre>
<pre><code>##   max(Price) - min(Price) IQR(Price)
## 1                    2985     2492.5</code></pre>
</div>
<div id="range-and-interquartile-range-of-carat" class="section level5">
<h5>Range and Interquartile Range of Carat</h5>
<pre class="r"><code>professor.proposes.data %&gt;%
  summarize(max(Carat) - min(Carat), IQR(Carat))</code></pre>
<pre><code>##   max(Carat) - min(Carat) IQR(Carat)
## 1                    1.49       0.71</code></pre>
</div>
</div>
<div id="histogram-and-distribution-ggplot" class="section level2">
<h2>Histogram and Distribution / ggplot</h2>
<pre class="r"><code>ggplot(professor.proposes.data, aes(y=Price, x=Carat)) + geom_point()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-35-1.png" width="672" />
#### We observe that there are two distinct clusters with low carat (0.09 – 0.30) diamonds having low prices and higher carat diamonds having higher prices.</p>
<pre class="r"><code>ggplot(professor.proposes.data, aes(x=Price, fill=Clarity)) + geom_histogram()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<pre class="r"><code>ggplot(professor.proposes.data, aes(x=Price, color=Cut)) + geom_density()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<pre class="r"><code>ggplot(professor.proposes.data) + 
  geom_bar(mapping = aes(x = Cut))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = professor.proposes.data, mapping = aes(x = Price, y = ..density..)) + 
  geom_freqpoly(mapping = aes(colour = Cut), binwidth = 500)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = professor.proposes.data, mapping = aes(x = Cut, y = Price)) +
  geom_boxplot()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = professor.proposes.data, mapping = aes(x = Carat, y = Price)) + 
  geom_boxplot(mapping = aes(group = cut_width(Carat, 0.1)))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<pre class="r"><code>ggplot(professor.proposes.data, aes(y=Price, x=Carat, color=Clarity, shape=Cut)) + geom_point()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<pre class="r"><code>ggplot(professor.proposes.data, aes(y=Price, x=Carat)) + geom_point() + geom_smooth()</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<pre class="r"><code>ggplot(professor.proposes.data, aes(y=Price, x=Carat)) + geom_point() + geom_smooth(se=FALSE)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<pre class="r"><code>ggplot(professor.proposes.data, aes(y=Price, x=Carat, color=Cut)) + geom_point() + facet_wrap(~ Clarity)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
</div>
<div id="linear-model" class="section level2">
<h2>Linear Model</h2>
<pre class="r"><code>m1 &lt;- lm(I(log(Price)) ~ I(Carat^(1/3)), data = professor.proposes.data)

m2 &lt;- update(m1, ~ . + Carat)
m3 &lt;- update(m2, ~ . + Cut)
m4 &lt;- update(m3, ~ . + Polish)
m5 &lt;- update(m4, ~ . + Clarity)
mtable(m1, m2, m3, m4, m5, sdigits=4)</code></pre>
<pre><code>## 
## Calls:
## m1: lm(formula = I(log(Price)) ~ I(Carat^(1/3)), data = professor.proposes.data)
## m2: lm(formula = I(log(Price)) ~ I(Carat^(1/3)) + Carat, data = professor.proposes.data)
## m3: lm(formula = I(log(Price)) ~ I(Carat^(1/3)) + Carat + Cut, data = professor.proposes.data)
## m4: lm(formula = I(log(Price)) ~ I(Carat^(1/3)) + Carat + Cut + Polish, 
##     data = professor.proposes.data)
## m5: lm(formula = I(log(Price)) ~ I(Carat^(1/3)) + Carat + Cut + Polish + 
##     Clarity, data = professor.proposes.data)
## 
## ==============================================================================
##                       m1          m2          m3          m4          m5      
## ------------------------------------------------------------------------------
##   (Intercept)       3.008***    1.143***    1.195***    1.222***    1.439***  
##                    (0.047)     (0.169)     (0.165)     (0.181)     (0.154)    
##   I(Carat^(1/3))    4.883***    8.603***    8.196***    7.760***    6.903***  
##                    (0.055)     (0.331)     (0.323)     (0.336)     (0.283)    
##   Carat                        -1.858***   -1.594***   -1.372***   -0.704***  
##                                (0.163)     (0.162)     (0.169)     (0.145)    
##   Cut: G/F                                  0.116**     0.106**     0.076**   
##                                            (0.036)     (0.035)     (0.029)    
##   Cut: I/F                                  0.184***    0.144***    0.117***  
##                                            (0.033)     (0.034)     (0.028)    
##   Cut: V/F                                  0.176***    0.159***    0.123***  
##                                            (0.034)     (0.034)     (0.028)    
##   Cut: X/F                                  0.072*      0.052       0.056*    
##                                            (0.029)     (0.030)     (0.024)    
##   Polish: G/F                                           0.178*      0.098     
##                                                        (0.082)     (0.069)    
##   Polish: I/F                                           0.522***    0.298**   
##                                                        (0.117)     (0.100)    
##   Polish: v/F                                           0.554**     0.313     
##                                                        (0.195)     (0.161)    
##   Polish: V/F                                           0.221**     0.098     
##                                                        (0.084)     (0.071)    
##   Polish: X/F                                           0.231**     0.111     
##                                                        (0.087)     (0.073)    
##   Clarity: I2                                                      -0.222***  
##                                                                    (0.033)    
##   Clarity: SI1                                                      0.264***  
##                                                                    (0.028)    
##   Clarity: SI2                                                      0.249***  
##                                                                    (0.025)    
##   Clarity: SI3                                                      0.022     
##                                                                    (0.034)    
##   Clarity: VS1                                                      0.296***  
##                                                                    (0.037)    
##   Clarity: VS2                                                      0.290***  
##                                                                    (0.034)    
##   Clarity: VVS1                                                     0.254*    
##                                                                    (0.107)    
##   Clarity: VVS2                                                     0.492***  
##                                                                    (0.071)    
## ------------------------------------------------------------------------------
##   R-squared         0.9471      0.9592      0.9631      0.9654      0.9776    
##   N               440         440         440         440         440         
## ==============================================================================
##   Significance: *** = p &lt; 0.001; ** = p &lt; 0.01; * = p &lt; 0.05</code></pre>
<div id="predictions" class="section level3">
<h3>Predictions</h3>
<pre class="r"><code>Diamond = data.frame(Carat = 0.92, Cut = &quot;G&quot;,
                         Polish = &quot;G&quot;, Clarity=&quot;SI2&quot;)
(modelEstimate = predict(m5, newdata = Diamond,
                        interval=&quot;prediction&quot;, level = .95) )</code></pre>
<pre><code>##        fit      lwr      upr
## 1 7.928063 7.640243 8.215883</code></pre>
<pre class="r"><code>exp(modelEstimate)</code></pre>
<pre><code>##        fit     lwr      upr
## 1 2774.049 2080.25 3699.241</code></pre>
</div>
</div>
